[toolchain]
anchor_version = "0.32.1"
solana_version = "2.0.3"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hyper_prediction = "5Svbs4ygkZBg6CpgmckTK35ZvACegFVW4F6hfbrhgE6v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
