[workspace]
members = [
    "programs/hyper_prediction"
]
exclude = [
    "programs/prediction_market",
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = true

[profile.dev]
overflow-checks = true




