[package]
name = "hyper_prediction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token", "metadata"] }
fixed = "1.26.0"

[features]
default = []

